# Generated by Django 5.0.2 on 2024-02-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='file',
        ),
    ]
